### ISSUE TITLE
Ilegal characters in path. (git bash windows)

### ISSUE THREAD

**Issue by santosdeva** [4lessandrodev/types-ddd-cli#1]
trying to run command ` types-ddd -g value-object -n sample` using **git bash** on windows system

![error-on-generate-types-ddd-file](https://user-images.githubusercontent.com/95001489/155126369-b57c1048-1378-4acf-b427-1e5e81546455.PNG)

```sh
$ echo $OSTYPE
> msys

$ uname
> MINGW64_NT-10.0-19044
```

**Comment by 4lessandrodev** [comment]
Hey @santosdeva thanks for share this issue.

I'm working to add support to windows. Currently the CLI works only in WSL and linux environments
